export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_EXIT = 'LOGIN_EXIT';
export const LOGIN_EXIT_REQUEST ='LOGIN_EXIT_REQUEST';
export const LOGIN_EXIT_FAILED ='LOGIN_EXIT_REQUEST';
